<?php

namespace AppBundle\Repository\QuoteRequest\JobCategory;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobCategoryRepository extends EntityRepository{


}
