<?php

namespace AppBundle\Repository\Service\Item;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository{

  public function getForDisplay(){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('i')->from('AppBundle\Entity\Service\Item\Item', 'i');

      $result = []; $row = [];
      foreach($data->getQuery()->getResult() as $r){

        $row[] = $r;

        if(sizeof($row) == 3){
          $result[] = $row;
          $row = [];
        }
      }

      if(sizeof($row) != 0){
        $result[] = $row;
      }

      return $result;
  }

}
