<?php

namespace AppBundle\Repository\Service\Item;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends Repository{

  public function getForDisplay(){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('i')->from('AppBundle\Entity\Service\Item\Item', 'i');

      $result = []; $row = [];
      foreach($data->getQuery()->getResult() as $r){

        $row[] = $r;

        if(sizeof($row) == 3){
          $result[] = $row;
          $row = [];
        }
      }

      if(sizeof($row) != 0){
        $result[] = $row;
      }

      return $result;
  }

  public function getPaginated($limit, $offset, $slidersPath){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('i')->from('AppBundle\Entity\Service\Item\Item', 'i');
      $data->setFirstResult($offset);
      $data->setMaxResults($limit);
      $data->orderBy('i.id', 'desc');

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(i.id)')->from('AppBundle\Entity\Service\Item\Item', 'i');
      $total = $count->getQuery()->getSingleScalarResult();

      $final = [];
      foreach($data->getQuery()->getResult() as $i){
        $final['data'][] = [
          'id' => $i->getId(),
          'title' => $i->getTitle(),
          'image_url' => $slidersPath.$i->getPath()
        ];
      }

      return $this->payload($total, $limit, $offset, $final);

  }

}
