<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Repository extends EntityRepository{

	public function payload($total, $limit, $offset, $result, $extraFields = []){

			$lastPage = ceil($total / $limit);
			$to =  ($offset * $limit) + $limit;
			if($to >= $total){
				$to = $total;
			}
			$from = (integer) ($offset * $limit) + 1;
			if($to == 0){
				$from = 0;
			}

			$currentPage = ceil($offset / $limit) + 1;

	    $return = [
          "total" => (integer) $total,
          "per_page" => (integer) $limit,
          "current_page" => (integer) $currentPage,
          "last_page" =>  (integer) ($lastPage == 0) ? 1 : $lastPage,
          "from" =>  $from,
          "to" => (integer) $to,
          "data" => $result
      ];

	    foreach($extraFields as $key => $value){
	        $return[$key] = $value;
	    }

			return $return;
	}
}
