<?php

namespace AppBundle\Repository\Subscriber;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubscriberRepository extends Repository{

  public function getPaginated($limit, $offset){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('i')->from('AppBundle\Entity\Subscriber\Subscriber', 'i');
      $data->setFirstResult($offset);
      $data->setMaxResults($limit);
      $data->orderBy('i.id', 'desc');
      $result = $data->getQuery()->getResult();

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(i.id)')->from('AppBundle\Entity\Subscriber\Subscriber', 'i');
      $total = $count->getQuery()->getSingleScalarResult();

      $final = [];
      foreach($result as $i){
          $final[] = [
            'id' => $i->getId(),
            'email' => $i->getEmail(),
            'created' => $i->getCreated()->format('Y-m-d')
          ];
      }

      return $this->payload($total, $limit, $offset, $final);

  }

  public function count(){

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(i.id)')->from('AppBundle\Entity\Subscriber\Subscriber', 'i');
      return $count->getQuery()->getSingleScalarResult();

  }

}
