<?php

namespace AppBundle\Repository\Offerpage;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferpageRepository extends Repository{


}
