<?php

namespace AppBundle\Repository\JobCategory;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobCategoryRepository extends Repository{

    public function getPaginated($limit, $offset){

        $data = $this->getEntityManager()->createQueryBuilder();
        $data->select('i')->from('AppBundle\Entity\JobCategory\JobCategory', 'i');
        $data->where('i.deleted_at is null');
        $data->setFirstResult($offset);
        $data->setMaxResults($limit);
        $data->orderBy('i.id', 'desc');
        $result = $data->getQuery()->getResult();

        $count = $this->getEntityManager()->createQueryBuilder();
        $count->select('count(i.id)')->from('AppBundle\Entity\JobCategory\JobCategory', 'i');
        $count->where('i.deleted_at is null');
        $total = $count->getQuery()->getSingleScalarResult();

        $final = [];
        foreach($result as $i){
          $final[] = [
            'id' => $i->getId(),
            'name' => $i->getName()
          ];
        }

        return $this->payload($total, $limit, $offset, $final);

    }
}
