<?php

namespace AppBundle\Repository\TeamMember;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamMemberRepository extends Repository{

  public function getPaginated($limit, $offset, $slidersPath){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('tm')->from('AppBundle\Entity\TeamMember\TeamMember', 'tm');
      $data->setFirstResult($offset);
      $data->setMaxResults($limit);
      $data->orderBy('tm.id', 'desc');

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(tm.id)')->from('AppBundle\Entity\TeamMember\TeamMember', 'tm');
      $total = $count->getQuery()->getSingleScalarResult();

      $final = [];
      foreach($data->getQuery()->getResult() as $item){
          $final[] = [
            'id' => $item->getId(),
            'name' => $item->getName(),
            'title' => $item->getTitle(),
            'image_url' => (is_null($item->getPath())) ? null : $slidersPath.$item->getPath()
          ];
      }

      return $this->payload($total, $limit, $offset, $final);

  }

}
