<?php

namespace AppBundle\Repository\Script;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScriptRepository extends Repository{

  public function getPaginated($limit, $offset){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('s')->from('AppBundle\Entity\Script\Script', 's');
      $data->setFirstResult($offset);
      $data->setMaxResults($limit);
      $data->orderBy('s.id', 'desc');
      $result = $data->getQuery()->getResult();

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(s.id)')->from('AppBundle\Entity\Script\Script', 's');
      $total = $count->getQuery()->getSingleScalarResult();

      $final = [];
      foreach($result as $i){
          $final[] = [
            'id' => $i->getId(),
            'name' => $i->getName(),
            'value' => $i->getValue()
          ];
      }

      return $this->payload($total, $limit, $offset, $final);

  }

}
