<?php

namespace AppBundle\Repository\Service\Item\File;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileRepository extends Repository{

  public function getPaginated($limit, $offset, $path){

      $data = $this->getEntityManager()->createQueryBuilder();
      $data->select('i')->from('AppBundle\Entity\Service\Item\File\File', 'i');
      $data->setFirstResult($offset);
      $data->setMaxResults($limit);
      $data->orderBy('i.id', 'desc');

      $count = $this->getEntityManager()->createQueryBuilder();
      $count->select('count(i.id)')->from('AppBundle\Entity\Service\Item\File\File', 'i');
      $total = $count->getQuery()->getSingleScalarResult();

      $final = [];
      foreach($data->getQuery()->getResult() as $i){
        $final[] = [
          'id' => $i->getId()
        ];
      }

      return $this->payload($total, $limit, $offset, $final);

  }

}
