<?php

namespace AppBundle\Repository\Page\Item;

use AppBundle\Repository\Repository;

/**
 * SiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends Repository{
	
	public function getPaginated($limit, $offset, $filters = [], $path=""){
		$data = $this->getEntityManager()->createQueryBuilder();
		$data->from('AppBundle\Entity\Page\Item\Item', 'i');
		$data->where('i.page = :id');
		$data->setParameter('id' , $filters['id'] );
		$data->andWhere('i.type = :type');
		$data->setParameter('type' , $filters['type'] );
	
		
	
		$count = clone $data;
		$count->select('count(i.id)');
		$total = $count->getQuery()->getSingleScalarResult();
	
		$data->select('i');
		if(!is_null($offset) && !is_null($limit)){
			$data->setFirstResult($offset);
			$data->setMaxResults($limit);
		}
		$result = $data->getQuery()->getResult();
	
		$final = [];
		foreach($result as $item){
			$result_page = [];
			$result_page['id'] = $item->getId();
			$result_page['title'] = $item->getTitle();
			$result_page['url'] = $path.$item->getWebPath();
			$result_page['featured'] = $item->getFeatured();
			$final[] = $result_page;
		}

		if(!is_null($offset) && !is_null($limit)){
			return $this->payload($total, $limit, $offset, $final);
		} else {
			return $final;
		}
	
	}
	
	public function clearFeaturedItems($page_id){
	
		$data = $this->getEntityManager()->createQueryBuilder();
			$q = $data->update( 'AppBundle\Entity\Page\Item\Item' ,'i')
			->set('i.featured', '?1')
			->where('i.page = :page_id')
			->setParameter('1', false)
			->setParameter('page_id', $page_id)
			->getQuery();
			$p = $q->execute();
	}
}
